import { Booth } from "../shared/types/asset_types";
import { availableAsset } from "../shared/util/functions";

export const BOOTH_MEMORIAL60_LIST: Booth[] = [
  new Booth({
    id: "1",
    order: 0,
    place: "60주년기념관",
    name: "총학본부-YOUR EVENT",
    description:
      "총학생회 X 하이트진로 맥주 빨리 마시기 대회\n주류 판매 부스에서 판매되는 맥주 360ml로 경기 진행",
    saleItems: [],
  }),
  new Booth({
    id: "2",
    order: 1,
    place: "60주년기념관",
    name: "주점",
    description: "60주년 주점 주류 및 음료 안내",
    saleItems: [
      { item: "참이슬 400ml", price: { min: 4000, max: 4000 } },
      { item: "테라, 켈리 360ml", price: { min: 4000, max: 4000 } },
      { item: "콜라, 사이다, 탐스제로 355ml", price: { min: 2000, max: 2000 } },
      { item: "anf 500ml", price: { min: 1000, max: 1000 } },
    ],
  }),
];
export const BOOTH_MIRAE_LIST: Booth[] = [
  new Booth({
    id: "a",
    order: 0,
    place: "미래광장",
    name: "주점",
    description: "미래광장 주점 주류 및 음료 안내",
    saleItems: [
      { item: "참이슬 400ml", price: { min: 4000, max: 4000 } },
      { item: "테라, 켈리 360ml", price: { min: 4000, max: 4000 } },
      { item: "콜라, 사이다, 탐스제로 355ml", price: { min: 2000, max: 2000 } },
      { item: "anf 500ml", price: { min: 1000, max: 1000 } },
    ],
  }),
];
export const BOOTH_PLAYGROUND_MIDDLE_YELLOW_LINE_LIST: Booth[] = [
  new Booth({
    id: "750ef3bc7b",
    order: 0,
    place: "대운중앙노랑",
    name: "코지존",
    description: "초록;을 보는 순간\n대운동장에서 즐기는 여유로운 휴식",
    saleItems: [],
  }),
  new Booth({
    id: "8ae87b7d0c",
    order: 1,
    place: "대운중앙노랑",
    name: "총학생회 본부",
    description: "분실물 관리 및 비상약품 구비\n대운동장 안전 관리 및 코지존 관리",
    saleItems: [],
  }),
  new Booth({
    id: "b61c7a2fe6",
    order: 2,
    place: "대운중앙노랑",
    name: "총학생회 본부(타투)",
    description: "소록;을 쌓는 순간\n백령대동제에서의 작은 기억을 남겨보아요!",
    saleItems: [],
    imageName: "8ae87b7d0c",
  }),
  new Booth({
    id: "fe8093b1051",
    order: 3,
    place: "대운중앙노랑",
    name: "단과대학제전",
    description: "기록;을 맺는 순간\n강원대학교 최고의 단과대학을 가리는 단과대학제전",
    saleItems: [],
    imageName: "8ae87b7d0c",
  }),
  new Booth({
    id: "fe8093b105",
    order: 4,
    place: "대운중앙노랑",
    name: "단과대학제전",
    description: "기록;을 맺는 순간\n강원대학교 최고의 단과대학을 가리는 단과대학제전",
    saleItems: [],
    imageName: "8ae87b7d0c",
  }),
  new Booth({
    id: "e5eec3f24d1",
    order: 5,
    place: "대운중앙노랑",
    name: "2024 백령대동제 굿즈 판매 및 수령",
    description: "백령인을 하나로 모을 대동제 한정판 굿즈 판매",
    saleItems: [],
    imageName: "8ae87b7d0c",
  }),
  new Booth({
    id: "e5eec3f24d",
    order: 6,
    place: "대운중앙노랑",
    name: "2024 백령대동제 굿즈 판매 및 수령",
    description: "백령인을 하나로 모을 대동제 한정판 굿즈 판매",
    saleItems: [],
    imageName: "8ae87b7d0c",
  }),
  new Booth({
    id: "1d9a23f27e",
    order: 7,
    place: "대운중앙노랑",
    name: "대학일자리플러스센터",
    description: "학생들의 수요에 맞는 다양한 프로그램을 기획해드립니다!",
    saleItems: [],
  }),
  new Booth({
    id: "fa178d3fa1",
    order: 8,
    place: "대운중앙노랑",
    name: "법무부 저스티스 서포터스 17기 SLS",
    description: "법무부 저스티스 서포터스와 함께 범죄예방정책 톺아보기!",
    saleItems: [],
  }),
  new Booth({
    id: "b25a73b0f6",
    order: 9,
    place: "대운중앙노랑",
    name: "학생권익위원회",
    description:
      "인사이드아웃2 in 권익위 “나의 감정들을 만나며 권익을 보장받는 시간“\n감정약국에서 처방받고, 감정 팔찌를 만들어보세요!",
    saleItems: [],
  }),
  new Booth({
    id: "35c8072ec1",
    order: 10,
    place: "대운중앙노랑",
    name: "문화발전위원회",
    description:
      "문화발전위원회가 무나해요!\n문발위와 도서관 문화 프로그램도 알아가고 도서관 퀴즈로 상품도 받아가고!",
    saleItems: [],
  }),
  new Booth({
    id: "02b75dfc25",
    order: 11,
    place: "대운중앙노랑",
    name: "빛길",
    description: "도박문제 헬프라인 1336을 뽑아라! 참여만 해도 상품이!\n",
    saleItems: [{ item: "참여만 해도 간식꾸러미 증정 (무료)", price: null }],
  }),
  new Booth({
    id: "c7f9627d65",
    order: 12,
    place: "대운중앙노랑",
    name: "가온",
    description: "본인과 맞는 친구를 사귀고 싶다면?! 가온 부스로 놀러 오세요♥",
    saleItems: [],
  }),
];

export const BOOTH_PLAYGROUND_BOTTOM_PINK_LINE_LIST: Booth[] = [
  new Booth({
    id: "d18e34a3c0",
    order: 1,
    name: "한국환경공단 강원환경본부 환경서비스처 제도운영부",
    description: "1회용품 줄이기 및 분리배출 등 공익 캠페인 운영\n분리배출 앱 설치 시 기념품 증정",
    saleItems: [],
    place: "대운하단분홍",
  }),
  availableAsset([
    new Booth({
      id: "c9b8f95d36",
      order: 2,
      name: "몽글리(월,화)",
      description: "예쁨 가득한 비누와 제스모나이트 소품을 제작하는 몽글리입니다.",
      saleItems: [{ item: "과일트레이", price: { min: 10000, max: 10000 } }],
      place: "대운하단분홍",
      date: [23, 24],
    }),
    new Booth({
      id: "c7b5e9b9d3",
      order: 2,
      name: "디어마(수)",
      description: "춘천의 봄날을 닮은 포근한 패브릭 소품을 만들어요:)",
      saleItems: [{ item: "파우치", price: { min: 4000, max: 40000 } }],
      place: "대운하단분홍",
      date: [25],
    }),
  ]),
  new Booth({
    id: "872d6c6cf5",
    order: 3,
    name: "미소유",
    description: "인생 경력 (셋이 합쳐) 69년차가 말아주는 컵 김치말이 국수와 팝만두",
    saleItems: [
      { item: "김치말이국수", price: { min: 4500, max: 4500 } },
      { item: "팝만두", price: { min: 2000, max: 2000 } },
      { item: "세트", price: { min: 6000, max: 6000 } },
    ],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "09eb7da1de",
    order: 4,
    name: "20주들",
    description: "일본식 빙수 '카키고오리'와 함께 특별한 순간을 달콤한 추억으로 물들이세요!",
    saleItems: [{ item: "시럽빙수", price: { min: 3000, max: 3000 } }],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "c19aa8be65",
    order: 5,
    name: "JDM",
    description: "대동제 원조 맛집 떡삼! 천국의 맛으로 여러분을 초대합니다!",
    saleItems: [
      { item: "떡삼", price: { min: 3000, max: 3000 } },
      { item: "콤보세트(떡삼2+음료1)", price: { min: 6500, max: 6500 } },
    ],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "50c1fce68a",
    order: 6,
    name: "강원대학교 4-H회",
    description: "게임과 함께 맛있는 와플&아이스크림 먹어요!",
    saleItems: [
      { item: "아이스크림&와플", price: { min: 3500, max: 3500 } },
      { item: "다트 풍선던지기", price: { min: 2500, max: 2500 } },
      { item: "네잎클로버", price: { min: 2000, max: 2000 } },
    ],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "73f46f69f4",
    order: 7,
    name: "테이스티타임",
    description: "오일장버거",
    saleItems: [],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "a217d2aa7a",
    order: 8,
    name: "팥타싼",
    description: "앗 팥빙수 타이어보다 싸다!!",
    saleItems: [
      { item: "타이어", price: { min: 350000, max: 350000 } },
      { item: "팥빙수", price: { min: 3500, max: 3500 } },
    ],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "ab4a0c15a2",
    order: 9,
    name: "이거좀마셔BAR",
    description: "거기 YOU 이거좀마셔BAR U 맛있어U 메뉴와 가격",
    saleItems: [
      { item: "셜리 템플", price: { min: 3500, max: 3500 } },
      { item: "바베이도스 서프라이즈", price: { min: 3900, max: 3900 } },
      { item: "블루 드래곤", price: { min: 3500, max: 3500 } },
      { item: "토마토 카나페 1SET(6개)", price: { min: 3000, max: 3000 } },
    ],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "e28aa0738e",
    order: 10,
    name: "웰컴 투 이스탄불",
    description: "입 안에 아쿠아리움 펼쳐지는 맛",
    saleItems: [{ item: "고등어케밥", price: { min: 5000, max: 5000 } }],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "f93f7d8c06",
    order: 11,
    name: "도화",
    description: "대학생 필수 비타민 여기 다 들어있다! 나랑.. 과일 스껄할래?",
    saleItems: [
      { item: "제철 생과일 컵", price: { min: 3000, max: 3000 } },
      { item: "제철 생과일 음료", price: { min: 3000, max: 3000 } },
      { item: "요거트 과일 화채", price: { min: 4000, max: 4000 } },
      { item: "생과일 + 에이드 콤보", price: { min: 5500, max: 5500 } },
    ],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "2996a8de2d",
    order: 12,
    name: "LinkU",
    description: "추억의 콜팝 & 슬러시",
    saleItems: [
      { item: "메론 슬러시", price: { min: 2000, max: 2000 } },
      { item: "슬러시 콜팝", price: { min: 3000, max: 3000 } },
    ],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "93d949f5e9",
    order: 13,
    name: "농사직썰",
    description: "농사직썰 회원들이 키운 농산물! 함께 나눠요~!🧑‍🌾",
    saleItems: [
      { item: "삼겹살", price: { min: 3000, max: 3000 } },
      { item: "감자전", price: { min: 3000, max: 3000 } },
      { item: "부추전", price: { min: 3000, max: 3000 } },
    ],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "4c06b8ef37",
    order: 14,
    name: "ALFS",
    description: "제로를 넘은 알러지 프리 디저트로 진정한 자유로움을 맛보세요!",
    saleItems: [{ item: "비스코티(2ea)", price: { min: 2500, max: 2500 } }],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "71e31bfc6e",
    order: 15,
    name: "디저트99",
    description: "무더운 여름날 아이스크림 하나 들고 가세요~",
    saleItems: [
      { item: "아이스크림", price: { min: 2000, max: 2000 } },
      { item: "아이스크림(토핑추가)", price: { min: 2500, max: 2500 } },
      { item: "아포가토", price: { min: 2500, max: 2500 } },
    ],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "67e3c1c3cc",
    order: 16,
    name: "홀로그램",
    description: "떡볶이 맛집 홀로그램에 많은 방문바랍니다!",
    saleItems: [
      { item: "떡볶이", price: { min: 4000, max: 4000 } },
      { item: "마라로제떡볶이", price: { min: 5000, max: 5000 } },
    ],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "36b68df0f4",
    order: 17,
    name: "도담상점",
    description: "반짝이는 비즈마을에 오신걸 환영합니다!",
    saleItems: [
      { item: "비즈키링", price: { min: 2000, max: 10000 } },
      { item: "비즈반지", price: { min: 2000, max: 10000 } },
      { item: "비즈팔찌", price: { min: 2000, max: 10000 } },
    ],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "ffb5da54d5",
    order: 18,
    name: "달리는푸드카페",
    description: "커피 ,직접 갈아만든 방울토마토 주스로 여러분을 찾아뵙겠습니다!",
    saleItems: [
      { item: "커피", price: { min: 4000, max: 5000 } },
      { item: "에이드", price: { min: 4000, max: 5000 } },
      { item: "식혜", price: { min: 4000, max: 5000 } },
      { item: "아이스티", price: { min: 4000, max: 5000 } },
      { item: "방울토마토주스 등", price: { min: 4000, max: 5000 } },
    ],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "7497d24939",
    order: 19,
    name: "준수비즈",
    description: "블링블링 러블리한 비즈 액세서리를 만듭니다.",
    saleItems: [
      { item: "스마트폰 스트랩", price: { min: 3000, max: 9000 } },
      { item: "키링", price: { min: 3000, max: 9000 } },
      { item: "팔찌", price: { min: 3000, max: 9000 } },
      { item: "반지", price: { min: 3000, max: 9000 } },
    ],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "e185176c19",
    order: 20,
    name: "풀가",
    description: "풀가의 털복숭이 칭구들",
    saleItems: [{ item: "캐릭터 문구 다꾸 리빙제품", price: { min: 2000, max: 2000 } }],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "cdd594c254",
    order: 21,
    name: "수미악세사리",
    description: "해마타이트 혈액순환을 도와주는 원석을 가공하여 만든 액세서리",
    saleItems: [
      { item: "힐링스톤", price: { min: 5000, max: 10000 } },
      { item: "와이어악세", price: { min: 5000, max: 10000 } },
    ],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "0c761c827e",
    order: 22,
    name: "쁘띠쁘띠",
    description: "고온의 온도에 유리를 녹여 만든 액세서리입니다.",
    saleItems: [{ item: "써지컬 유리반지", price: { min: 15000, max: 15000 } }],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "9c5d6a5577",
    order: 23,
    name: "개인의취향",
    description: "귀여운 캐릭터 모양에 예븐 파츠를 응용하여 만든 석고 방향제입니다!",
    saleItems: [{ item: "석고방향제", price: { min: 8000, max: 8000 } }],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "43c62c61f9",
    order: 24,
    name: "공간잡화점",
    description: "자개악세사리, 헤어제품, 키링 등 여러가지 제품을 만듭니다.",
    saleItems: [{ item: "자개 오픈팔찌", price: { min: 8000, max: 8000 } }],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "8a18754738",
    order: 25,
    name: "향기운",
    description: "향기로 공간을 꾸며주세요.",
    saleItems: [{ item: "석고 방향제", price: { min: 5000, max: 20000 } }],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "27c55c0463",
    order: 26,
    name: "안방과연필",
    description: "100% 핸드메이드 아기자기 코바늘 소품",
    saleItems: [
      { item: "코바늘소품(키링,인형,가방,파우치 등)", price: { min: 3000, max: 120000 } },
    ],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "327afcdba7",
    order: 27,
    name: "HESSDOLL",
    description: "인형놀이를 위한 뜨개, 가방이나 모자 등 소품도 취급해요!",
    saleItems: [
      { item: "뜨개, 소품", price: { min: 20000, max: 50000 } },
      { item: "키링", price: { min: 0, max: 5000 } },
    ],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "0c96d9a479",
    order: 28,
    name: "나나쭈니",
    description: "다양한 지비츠를 판매합니다.",
    saleItems: [{ item: "지비츠", price: { min: 5000, max: 5000 } }],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "1c1d260dc6",
    order: 29,
    name: "시월의주",
    description: "진주/원석/실버 액세서리 판매합니다.",
    saleItems: [{ item: "원석 실버 목걸이", price: { min: 15000, max: 50000 } }],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "02ab7987ed",
    order: 30,
    name: "언니의 공예방",
    description: "생화, 자개 등 자연물을 직접 디자인하여 특별한 액세서리를 만듭니다.",
    saleItems: [{ item: "생화 액세서리", price: { min: 7000, max: 23000 } }],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "19aa65aa9d",
    order: 31,
    name: "이에스몰",
    description: "수제 문구류와 싸지컬 비즈 액세서리를 판매합니다.",
    saleItems: [
      { item: "문구류", price: { min: 800, max: 800 } },
      { item: "액세서리", price: { min: 3000, max: 3000 } },
    ],
    place: "대운하단분홍",
  }),
  availableAsset([
    new Booth({
      id: "23e09c30f3",
      order: 32,
      name: "스링(월,수)",
      description: "저연스러움을 추구하는 주얼리",
      saleItems: [{ item: "파도하트 목걸이", price: { min: 35000, max: 35000 } }],
      place: "대운하단분홍",
      date: [23, 25],
    }),
    new Booth({
      id: "1e70e18f7f",
      order: 32,
      name: "강원FC Playground(화)",
      description: "미니골대 활용한 축구게임 진행\n구단 홍보물 및 경품 증정",
      saleItems: [],
      place: "대운하단분홍",
      date: [24],
    }),
  ]),
  new Booth({
    id: "a57dbe82b5",
    order: 33,
    name: "작심",
    description: "일상 속 '마음 짓기'에 필요한 제품을 만듭니다.",
    saleItems: [{ item: "미니카드, 해빗, 트래커 등", price: { min: 2000, max: 2000 } }],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "bded94c18d",
    order: 34,
    name: "도담메이드",
    description: "귀엽고 포근포근한, 일사으이 패브릭 소품을 만듭니다.",
    saleItems: [
      { item: "손수건", price: { min: 3900, max: 5900 } },
      { item: "거즈담요", price: { min: 3900, max: 5900 } },
      { item: "기타", price: { min: 13000, max: 13000 } },
    ],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "ac2902d6e4",
    order: 35,
    name: "사주",
    description:
      "새로운 시작을 앞두고 있거나, 인생의 전환점을 맞이한 여러분, 사주와 운세를 통해 자신을 더 깊이 이해해 보세요.",
    saleItems: [
      { item: "사주", price: { min: 5000, max: 5000 } },
      { item: "타로", price: { min: 3000, max: 3000 } },
    ],
    place: "대운하단분홍",
  }),
  new Booth({
    id: "c2f1a6d0d8",
    order: 36,
    name: "사주",
    description:
      "새로운 시작을 앞두고 있거나, 인생의 전환점을 맞이한 여러분, 사주와 운세를 통해 자신을 더 깊이 이해해 보세요.",
    saleItems: [
      { item: "사주", price: { min: 5000, max: 5000 } },
      { item: "타로", price: { min: 3000, max: 3000 } },
    ],
    place: "대운하단분홍",
    imageName: "ac2902d6e4",
  }),
];

export const BOOTH_PLAYGROUND_TOP_GREEN_LINE_LIST: Booth[] = [
  new Booth({
    id: "7c4e5392f1",
    order: 1,
    name: "8llow me",
    description:
      "“몸에 좋고, 맛도 좋은” 해발 600m 정선에서 슈퍼푸드 블루베리를 유기농으로 재배했습니다.",
    saleItems: [
      { item: "블루베리 에이드", price: { min: 3900, max: 3900 } },
      { item: "블루베리 누룽지", price: { min: 2000, max: 2000 } },
    ],
    place: "대운상단초록",
  }),
  new Booth({
    id: "a4e2f07a2d",
    order: 2,
    name: "타로세이",
    description: "사주&타로 운세상담 (TAROTSAY)",
    saleItems: [],
    place: "대운상단초록",
  }),
  new Booth({
    id: "b5f1c98b87",
    order: 3,
    name: "언럭키비키",
    description: "당신의 행운을 찾아가세요 !",
    saleItems: [{ item: "네잎클로버 투명코팅 카드", price: { min: 2000, max: 2000 } }],
    place: "대운상단초록",
  }),
  new Booth({
    id: "c16a8c9a99",
    order: 4,
    name: "곰탱이",
    description: "반려곰 한마리 데리고 가세요~TY 빈티지 인형",
    saleItems: [
      { item: "TY 곰인형", price: { min: 15000, max: null } },
      { item: "TY 동물인형", price: { min: 10000, max: null } },
    ],
    place: "대운상단초록",
  }),
  new Booth({
    id: "d3f485f084",
    order: 5,
    name: "강원대학교 구내안경원",
    description: "강원대학교 천지관 1층에 위치한 구내안경원입니다!",
    saleItems: [{ item: "창고 정리 파격 세일!", price: { min: null, max: null } }],
    place: "대운상단초록",
  }),
  new Booth({
    id: "e50315b49f",
    order: 6,
    name: "홀티팩토리",
    description: "행운이 가득한 압화레진공예와 개성있는 화분이 모여있는 곳으로 초대합니다!",
    saleItems: [
      { item: "바질화분", price: { min: 7000, max: 7000 } },
      { item: "이오난사 DIY화분 키트", price: { min: 7000, max: 7000 } },
    ],
    place: "대운상단초록",
  }),
  new Booth({
    id: "f3e14ef65f",
    order: 7,
    name: "크레세르",
    description: "식물가게 CRECER에서 자연의 싱그러움을 만나보세요-자라나는 기쁨을 함께 나눕니다.",
    saleItems: [
      { item: "꽃다발", price: { min: 5000, max: 5000 } },
      { item: "화분", price: { min: 8000, max: null } },
    ],
    place: "대운상단초록",
  }),
  new Booth({
    id: "5c5a0e6c9f",
    order: 8,
    name: "FOR X",
    description: "♡ 오리지널 감자빵 FOR U ♡",
    saleItems: [{ item: "감자빵", price: { min: 3500, max: 3500 } }],
    place: "대운상단초록",
  }),
  new Booth({
    id: "245e6a34b4",
    order: 9,
    name: "별과함께",
    description: "떠오르는 브랜드 티파니앤코파니 귀여운 체인목걸이 & 키링 보러 방문해주세요!!",
    saleItems: [
      { item: "하트클로버 목걸이", price: { min: null, max: 9900 } },
      { item: "보송보송 인형키링", price: { min: 3500, max: 3500 } },
    ],
    place: "대운상단초록",
  }),
  new Booth({
    id: "fb6b60c6c1",
    order: 10,
    name: "아찔보이즈",
    description: "실크스크린 기법으로 직접 제작한 맛있는 후드티와 뜨개키링!!",
    saleItems: [
      { item: "후드티", price: { min: 37900, max: 37900 } },
      { item: "뜨개키링", price: { min: 5000, max: 5000 } },
    ],
    place: "대운상단초록",
  }),
  new Booth({
    id: "19ff8c4742",
    order: 11,
    name: "강원대 운동부 서포터즈",
    description: "강원대학교 운동부를 소개합니다:)",
    saleItems: [
      { item: "이벤트 참가비", price: { min: 1000, max: 1000 } },
      { item: "상품: 스티커, 키링, 인형", price: { min: null, max: null } },
    ],
    place: "대운상단초록",
  }),
  new Booth({
    id: "2d541fcfe0",
    order: 12,
    name: "우리다누리",
    description: "필요한 만큼 챙겨가세요 행복충전소",
    saleItems: [
      { item: "전통매듭키링", price: { min: null, max: null } },
      { item: "슈링클스키링과 다양한 게임까지 전부 무료", price: { min: null, max: null } },
    ],
    place: "대운상단초록",
  }),
  new Booth({
    id: "c021dfddfc",
    order: 13,
    name: "우쟈우쟈",
    description: "힙한 청바지 가방과 귀여운 뜨개키링을 한곳에서!",
    saleItems: [
      { item: "가방", price: { min: 35000, max: 35000 } },
      { item: "복조리파우치", price: { min: 5000, max: 10000 } },
      { item: "뜨개키링", price: { min: 5000, max: 10000 } },
    ],
    place: "대운상단초록",
  }),
  new Booth({
    id: "db9d8e9f8b",
    order: 14,
    name: "자치기구발전위원회",
    description: "그대의 추억을 직접 만드는 키링과 지비츠 속에..",
    saleItems: [
      { item: "셀프메이드 지비츠/키링(공방)", price: { min: 2000, max: 2000 } },
      { item: "완제품 지비츠", price: { min: 2000, max: 2000 } },
    ],
    place: "대운상단초록",
  }),
  new Booth({
    id: "79b97f6040",
    order: 15,
    name: "천지창조 주얼리",
    description: "천지와 미소녀들이 만든 커여운 주얼리 보고가세요 ♥",
    saleItems: [
      { item: "비즈 반지", price: { min: 1200, max: null } },
      { item: "비즈 팔찌", price: { min: 3000, max: 3000 } },
      { item: "비즈 목걸이", price: { min: 4000, max: 4000 } },
      { item: "키링", price: { min: 1800, max: null } },
      { item: "손뜨개키링", price: { min: 4000, max: 4000 } },
    ],
    place: "대운상단초록",
  }),
  new Booth({
    id: "3c7d8e6c3b",
    order: 16,
    name: "뭉개구름",
    description: "강아지의 사랑스러운 모습을 담은 굿즈를 받고 유기견 보호소에 기부하세요!",
    saleItems: [
      { item: "키링", price: { min: 3000, max: 3000 } },
      { item: "그립톡", price: { min: 3000, max: 3000 } },
      { item: "스티커", price: { min: 2500, max: 2500 } },
    ],
    place: "대운상단초록",
  }),
  new Booth({
    id: "4a8f5b2348",
    order: 17,
    name: "_isname",
    description: '감성 주얼리 소품샵 “_isname"',
    saleItems: [
      { item: "뜨개키링", price: { min: 2000, max: null } },
      { item: "목걸이", price: { min: 6500, max: 6500 } },
    ],
    place: "대운상단초록",
  }),
  new Booth({
    id: "e0c77622d5",
    order: 18,
    name: "워치친구들",
    description: "가격은 가볍게! 실용성은 높게! 다양한 워치 스트랩으로 스타일을 더하세요!",
    saleItems: [
      { item: "실리콘 스트랩(8종)", price: { min: 3000, max: 3000 } },
      { item: "벨크로 스트랩(6종)", price: { min: 3500, max: 3500 } },
      { item: "가죽 스트랩(20종)", price: { min: 4000, max: 4000 } },
      { item: "랜덤박스(스트랩 3개)", price: { min: 7000, max: 7000 } },
    ],
    place: "대운상단초록",
  }),
  new Booth({
    id: "6e57a5c0d4",
    order: 19,
    name: "푸더바",
    description: "핸드폰, 가방, 다이어리에 꾸미면 착붙인 스티커&키링",
    saleItems: [
      { item: "힙스터 키링", price: { min: 4300, max: 4300 } },
      { item: "힙스터 스티커팩", price: { min: 3700, max: 3700 } },
      { item: "말풍선 스티커", price: { min: 2500, max: 2500 } },
      { item: "티셔츠", price: { min: 29000, max: 29000 } },
    ],
    place: "대운상단초록",
  }),
  new Booth({
    id: "74d516f478",
    order: 20,
    name: "줄루아카이브",
    description: "“archive : 기록 보관소 빈티지와 구제 사이”",
    saleItems: [{ item: "폴로 셔츠", price: { min: 25000, max: 25000 } }],
    place: "대운상단초록",
  }),
  new Booth({
    id: "5971e1cd7f",
    order: 21,
    name: "OECO",
    description: "당신이 상상하는 모든 자연을 선물합니다",
    saleItems: [{ item: "생물 스티커", price: { min: 500, max: 500 } }],
    place: "대운상단초록",
  }),
  new Booth({
    id: "b56c4791b6",
    order: 22,
    name: "다함께퐁타타",
    description: "꽁꽁 얼어붙은 팔뚝위로 잉어 한마리가 걸어다닙니다",
    saleItems: [
      { item: "타투 스티커 포인트", price: { min: 1000, max: 1000 } },
      { item: "타투 스티커 중형1", price: { min: 3000, max: 3000 } },
      { item: "타투 스티커 대형", price: { min: 5000, max: 5000 } },
    ],
    place: "대운상단초록",
  }),
  new Booth({
    id: "c8db2c5e3f",
    order: 23,
    name: "액션(AC7OIN)",
    description: "제로음료를 사면 컵이 무료!",
    saleItems: [
      { item: "얼박사+컵", price: { min: 5000, max: 5000 } },
      { item: "밀키블루소다+컵", price: { min: 5500, max: 5500 } },
    ],
    place: "대운상단초록",
  }),
  new Booth({
    id: "b5a95ac64b",
    order: 24,
    name: "0304",
    description: "정성이 가득한 100% 핸드메이드 다양한 뜨개 인형과 비즈 악세사리",
    saleItems: [
      { item: "토끼 인형키링", price: { min: 16000, max: 16000 } },
      { item: "꿀벌 인형키링", price: { min: 13000, max: 13000 } },
      { item: "체리비즈팔찌", price: { min: 3500, max: 3500 } },
    ],
    place: "대운상단초록",
  }),
];

export const BOOTH_HAMINSEOP_LIST: Booth[] = [
  new Booth({
    id: "f1d780f09e",
    order: 0,
    name: "글로컬대학사업추진단 (연적지 삼거리 쪽)",
    description: "배너 및 미니게임을 이용한 글로컬대학사업 학생들이 받을 수 있는 혜택 홍보",
    saleItems: [],
    place: "함인섭",
  }),
  new Booth({
    id: "3c8f3e0f300f",
    order: 1,
    name: "강원대학교 총동창회(수)",
    description: "한우버거 및 한우불고기 나눔",
    saleItems: [],
    place: "함인섭",
  }),
  new Booth({
    id: "6e5c539c70",
    order: 1,
    name: "강원대학교 산학협력단(월, 화)",
    description: "교내 산학협력 유관기관 홍보",
    saleItems: [],
    place: "함인섭",
  }),
  new Booth({
    id: "a2c70d317e",
    order: 2,
    name: "강원대학교 산학협력단",
    description:
      "산학협력단 홍보 AR·VR 체험 및 레트로 게임기 체험 산학협력 수학능력시험 시행 및 경품 제공",
    saleItems: [],
    place: "함인섭",
    imageName: "6e5c539c70",
  }),
  new Booth({
    id: "5c8f68ef8a",
    order: 3,
    name: "강원대학교 산학협력단",
    description:
      "산학협력단 홍보 AR·VR 체험 및 레트로 게임기 체험 산학협력 수학능력시험 시행 및 경품 제공",
    saleItems: [],
    place: "함인섭",
    imageName: "6e5c539c70",
  }),
  new Booth({
    id: "d5dabc2c90",
    order: 4,
    name: "강원대학교 산학협력단",
    description:
      "산학협력단 홍보 AR·VR 체험 및 레트로 게임기 체험 산학협력 수학능력시험 시행 및 경품 제공",
    saleItems: [],
    place: "함인섭",
    imageName: "6e5c539c70",
  }),
  new Booth({
    id: "c0f81aedd0",
    order: 5,
    name: "강원대학교 산학협력단",
    description:
      "산학협력단 홍보 AR·VR 체험 및 레트로 게임기 체험 산학협력 수학능력시험 시행 및 경품 제공",
    saleItems: [],
    place: "함인섭",
    imageName: "6e5c539c70",
  }),
  new Booth({
    id: "c0f81sidd0",
    order: 6,
    name: "강원대학교 산학협력단",
    description:
      "산학협력단 홍보 AR·VR 체험 및 레트로 게임기 체험 산학협력 수학능력시험 시행 및 경품 제공",
    saleItems: [],
    place: "함인섭",
    imageName: "6e5c539c70",
  }),
  new Booth({
    id: "bd9e03b15d",
    order: 7,
    name: "ms홀딩스",
    description: "우동착 오더를 이용한 포토부스 촬영 오더 사용 후 방문 시 간단한 경품 증정",
    saleItems: [],
    place: "함인섭",
  }),
  new Booth({
    id: "a2e14a47c0",
    order: 8,
    name: "ms홀딩스",
    description: "우동착 오더를 이용한 포토부스 촬영 오더 사용 후 방문 시 간단한 경품 증정",
    saleItems: [],
    place: "함인섭",
    imageName: "bd9e03b15d",
  }),
  new Booth({
    id: "2725a49b98",
    order: 9,
    name: "한국건강관리협회 강원특별자치도지부",
    description: "뇌파·맥파 스트레스 검사 및 결과 설명 참가자 대상 기념품 증정",
    saleItems: [],
    place: "함인섭",
  }),
  new Booth({
    id: "21b0e689b8",
    order: 10,
    name: "총학생회 본부(재학생존 팔찌 배부)",
    description: "분실물 관리 및 비상약품 구비 함인섭광장 전반 관리(푸드트럭) 재학생 팔찌 배부",
    saleItems: [],
    place: "함인섭",
  }),
  new Booth({
    id: "5d8c5b2823",
    order: 11,
    name: "강원대학교 언어연수과",
    description: "교내 운영 외국어강좌 프로그램 소개",
    saleItems: [],
    place: "함인섭",
  }),
  new Booth({
    id: "3c8f3e0f3f",
    order: 12,
    name: "강원대학교 언어연수과",
    description: "교내 운영 외국어강좌 프로그램 소개",
    saleItems: [],
    place: "함인섭",
    imageName: "5d8c5b2823",
  }),
  new Booth({
    id: "92cb250c6c",
    order: 13,
    name: "강원지방병무청(병역진로설계지원센터)",
    description:
      "직업선호도 검사·전공·자격면허 연계 1:1 상담 설계참여자 대상 기념품 증정 병역진로설계사업 및 센터홍보 전투식량 체험 진행",
    saleItems: [],
    place: "함인섭",
  }),
  new Booth({
    id: "dbed85b1fa",
    order: 14,
    name: "127 ROTC",
    description: "학군단 추가모집 홍보 다트 던지기 & 장난감 총 사격 체험 부스 운영",
    saleItems: [],
    place: "함인섭",
  }),
  new Booth({
    id: "c44c2d5c99",
    order: 15,
    name: "강원대학교 정보화본부",
    description:
      "모의수강신청, 메타버스 등 대학 주요 정보서비스 체험 공용소프트웨어 소개, 웹메일을 활용한 Office 365 가입절차 안내 대학 무선네트워크 AP 종류 소개 및 정보보안수칙 안내 활동 참가자 대상 텀블러 제공",
    saleItems: [],
    place: "함인섭",
  }),
  new Booth({
    id: "d124837f30",
    order: 16,
    name: "강원권 미세먼지연구관리센터",
    description: "센터 홍보 및 미세먼지 관련 정보 전달 OX퀴즈 등 프로그램을 통한 기념품 배부",
    saleItems: [],
    place: "함인섭",
  }),
  new Booth({
    id: "2b1799bb36",
    order: 17,
    name: "춘천시청(자치행정과)",
    description: "인구정책 관련 간이 설문 진행 전입장려금 신청 운영",
    saleItems: [],
    place: "함인섭",
  }),
  new Booth({
    id: "6c6ab0e453",
    order: 18,
    name: "육군",
    description: "군 정보 제공 및 직업군인 상담 참가자 대상 소정의 기념품 증정",
    saleItems: [],
    place: "함인섭",
  }),
  new Booth({
    id: "ba5dc5bb7b",
    order: 19,
    name: "강원대학교 국제교류과",
    description:
      "국제교류과 소개 및 운영 프로그램 홍보 학생 상담 참가자 대상 이벤트 진행 후 기념품 증정",
    saleItems: [],
    place: "함인섭",
  }),
  availableAsset([
    new Booth({
      id: "7c5910d4f4",
      order: 20,
      name: "강원대학교 국제교류과(9/23, 9/25)",
      description:
        "국제교류과 소개 및 운영 프로그램 홍보 학생 상담 참가자 대상 이벤트 진행 후 기념품 증정",
      saleItems: [],
      place: "함인섭",
      imageName: "ba5dc5bb7b",
      date: [23, 25],
    }),
    new Booth({
      id: "9f79b8e2f4",
      order: 20,
      name: "강원국제개발협력센터(9/24)",
      description:
        "해외봉사단 및 국제개발협력 분야 설명회 1:1 컨설팅 진행 예정 참여자 대상 기념품 및 상품 증정",
      saleItems: [],
      place: "함인섭",
      date: [24],
    }),
  ]),
  new Booth({
    id: "49f69b9c54",
    order: 21,
    name: "NH농협은행 강원영업부",
    description: "NH농협은행 채용설명회 & 디지털 금융 상품 가입 시 뽑기 이벤트",
    saleItems: [],
    place: "함인섭",
  }),
  new Booth({
    id: "b08f40b5fa",
    order: 22,
    name: "NH농협은행 강원영업부",
    description: "NH농협은행 채용설명회 & 디지털 금융 상품 가입 시 뽑기 이벤트",
    saleItems: [],
    place: "함인섭",
    imageName: "49f69b9c54",
  }),
  new Booth({
    id: "8c6e3c5d2d",
    order: 23,
    name: "그린업(춘천E컵)",
    description:
      "E컵 사용자에게 구슬아이스크림 무료 배부 E컵과 탄소중립포인트 적립 홍보 교내 카페 2천원 쿠폰 배부 이벤트 진행",
    saleItems: [],
    place: "함인섭",
  }),
  new Booth({
    id: "90c0c7a4c7",
    order: 24,
    name: "㈜케이메디켐",
    description:
      "기능성 화장품 3종 체험 할인판매(1+1 행사) 이벤트 진행 SNS 이벤트를 통한 소정의 상품 제공",
    saleItems: [],
    place: "함인섭",
  }),
  new Booth({
    id: "3a14f90d3b",
    order: 25,
    name: "㈜컨플",
    description:
      "돌핀' 앱 팝업 전시를 활용한 게임 및 체험 참가자 대상 전문 프로필 사진 시그니쳐 패키지 무료 촬영권 추첨",
    saleItems: [],
    place: "함인섭",
  }),
  new Booth({
    id: "a1a4d1b1cf",
    order: 26,
    name: "재단법인 강원관광재단",
    description: "강원관광재단 홍보 외국인 유학생 참여 SNS이벤트 룰렛 이벤트",
    saleItems: [],
    place: "함인섭",
  }),
  availableAsset([
    new Booth({
      id: "ff6f6aa9f8",
      order: 27,
      name: "근화동_쁘미브레드(9/23)",
      description:
        "국내산 쌀과 현미가루를 사용해 쫄깃함을 더 업 시켜준 건강한 쌀베이글, 발효 버터를 사용해 깊은 맛과 풍미가 잘 어울어진 겉바속촉 쌀휘낭시에",
      saleItems: [],
      place: "함인섭",
      date: [23],
    }),
    new Booth({
      id: "3c68f8eaf2",
      order: 27,
      name: "학생상담센터 학습상담실(9/24)",
      description:
        "학생상담센터 학습상담실 이용안내 및 학습상담 다이렉트 신청 SNS계정 팔로우 이벤트를 통한 홍보물 제공",
      saleItems: [],
      place: "함인섭",
      date: [24],
    }),
    new Booth({
      id: "b8c04518c0",
      order: 27,
      name: "학생상담센터(9/25)",
      description:
        "스트레스 측정 및 심리상담 진행 정신건강 지원 캠페인 진행 잠가자 대상 홍보 물품 제공",
      saleItems: [],
      place: "함인섭",
      date: [25],
    }),
  ]),
  availableAsset([
    new Booth({
      id: "49b7801be8",
      order: 28,
      name: "여성가족인권상담센터 '한삶'(9/23)",
      description: "QR 질문 참여 통한 기관홍보 OX퀴즈 및 뽑기 퀴즈 진행 참가자 대상 홍보물품 증정",
      saleItems: [],
      place: "함인섭",
      date: [23],
    }),
    new Booth({
      id: "fc7e7fda5f",
      order: 28,
      name: "(사)강원여성인권지원공동체(9/24)",
      description: "성매매방지 OX퀴즈판 운영 퀴즈 성공 시 홍보물품 증정",
      saleItems: [],
      place: "함인섭",
      date: [24],
    }),
    new Booth({
      id: "0b9b4a7c3b",
      order: 28,
      name: "(재)착한목자수녀회(9/25)",
      description: "여성폭력피해상담 및 결혼이주여성상담정보 제공",
      saleItems: [],
      place: "함인섭",
      date: [25],
    }),
  ]),
];
