import { FoodTruck } from "../shared/types/asset_types";

export const FOODTRUCK_60TH_ANNIV_LIST: FoodTruck[] = [
  new FoodTruck({
    id: "cfa60e2f3e",
    order: 1,
    name: "위키스마일",
    menu: ["분식"],
    place: "60주년기념관",
  }),
  new FoodTruck({
    id: "dd840a637b",
    order: 2,
    name: "체리블라썸",
    menu: ["소떡소떡 외 기타"],
    place: "60주년기념관",
  }),
  new FoodTruck({
    id: "c8a7090348",
    order: 3,
    name: "뷰카페",
    menu: ["크레페"],
    place: "60주년기념관",
  }),
  new FoodTruck({
    id: "ef7acfd49f",
    order: 4,
    name: "메이트럭",
    menu: ["불초밥"],
    place: "60주년기념관",
  }),
  new FoodTruck({
    id: "9f676aeabe",
    order: 5,
    name: "오픈더키친",
    menu: ["야끼소바"],
    place: "60주년기념관",
  }),
  new FoodTruck({
    id: "5eaf2e31d2",
    order: 6,
    name: "춘향전",
    menu: ["김치전"],
    place: "60주년기념관",
  }),
  new FoodTruck({
    id: "acb1c8dfed",
    order: 7,
    name: "오올라",
    menu: ["타코"],
    place: "60주년기념관",
  }),
  new FoodTruck({
    id: "07b72f1c8c",
    order: 8,
    name: "럭키비키",
    menu: ["감자치즈볼"],
    place: "60주년기념관",
  }),
  new FoodTruck({
    id: "91e0c4b1cb",
    order: 9,
    name: "츄러스앤디저트",
    menu: ["츄러스"],
    place: "60주년기념관",
  }),
  new FoodTruck({
    id: "64e499c2db",
    order: 10,
    name: "곱창좋은날",
    menu: ["순대곱창"],
    place: "60주년기념관",
  }),
  new FoodTruck({
    id: "b9f1d2a1f8",
    order: 11,
    name: "푸드캐스팅",
    menu: ["닭꼬치"],
    place: "60주년기념관",
  }),
  new FoodTruck({
    id: "a0dfb2e0a4",
    order: 12,
    name: "고스트",
    menu: ["스테이크"],
    place: "60주년기념관",
  }),
  new FoodTruck({
    id: "42ff792b54",
    order: 13,
    name: "믹스",
    menu: ["크림새우"],
    place: "60주년기념관",
  }),
  new FoodTruck({
    id: "7e66b6f57e",
    order: 14,
    name: "듀피에",
    menu: ["피자"],
    place: "60주년기념관",
  }),
  new FoodTruck({
    id: "1d673ae5f7",
    order: 15,
    name: "듀피에",
    menu: ["닭강정"],
    place: "60주년기념관",
  }),
  new FoodTruck({
    id: "b792fd7a32",
    order: 16,
    name: "그양반네",
    menu: ["타코야끼"],
    place: "60주년기념관",
  }),
  new FoodTruck({
    id: "40c1e5aee2",
    order: 17,
    name: "곰두마리",
    menu: ["닭강정"],
    place: "60주년기념관",
  }),
  new FoodTruck({
    id: "5f04b43167",
    order: 18,
    name: "아임스크림",
    menu: ["아이스크림"],
    place: "60주년기념관",
  }),
  new FoodTruck({
    id: "dce6b5f90b",
    order: 19,
    name: "미스터블랙",
    menu: ["흑돼지덮밥"],
    place: "60주년기념관",
  }),
];

export const FOODTRUCK_FUTURE_LIST: FoodTruck[] = [
  new FoodTruck({
    id: "dce6b5f90b",
    order: 1,
    name: "미스터블랙",
    menu: ["흑돼지덮밥"],
    place: "미래광장",
  }),
  new FoodTruck({
    id: "40c1e5aee2",
    order: 2,
    name: "닭강정",
    menu: ["닭강정"],
    place: "미래광장",
  }),
  new FoodTruck({
    id: "7e66b6f57e",
    order: 3,
    name: "진츄",
    menu: ["소프트아이스크림"],
    place: "미래광장",
  }),
  new FoodTruck({
    id: "b792fd7a32",
    order: 4,
    name: "그양반네",
    menu: ["타코야끼"],
    place: "미래광장",
  }),
];

export const FOODTRUCK_HAMINSEOP_LIST: FoodTruck[] = [
  new FoodTruck({
    id: "dce6b5f90b1",
    order: 1,
    name: "미스터블랙",
    menu: ["흑돼지덮밥"],
    place: "미래광장",
  }),
  new FoodTruck({
    id: "40c1e5aee21",
    order: 2,
    name: "닭강정",
    menu: ["닭강정"],
    place: "미래광장",
  }),
  new FoodTruck({
    id: "7e66b6f57e1",
    order: 3,
    name: "진츄",
    menu: ["소프트아이스크림"],
    place: "미래광장",
  }),
  new FoodTruck({
    id: "b792fd7a321",
    order: 4,
    name: "그양반네",
    menu: ["타코야끼"],
    place: "미래광장",
  }),
  new FoodTruck({
    id: "random1",
    order: 5,
    name: "랜덤",
    menu: ["랜덤"],
    place: "미래광장",
  }),
  new FoodTruck({
    id: "random2",
    order: 6,
    name: "랜덤",
    menu: ["랜덤"],
    place: "미래광장",
  }),
  new FoodTruck({
    id: "random3",
    order: 7,
    name: "랜덤",
    menu: ["랜덤"],
    place: "미래광장",
  }),
];
